# This file was generated by GoReleaser. DO NOT EDIT.
cask "tars" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/tars"]
    end
  end

  version "0.1.18"

  on_macos do
    on_arm do
      sha256 "3e797ab0f43503052d17ffc5fdf5dd64f85b0d84c2641adef757724f7f2fcd12"
      url "https://github.com/cloudwalksolutions/machine-setup/releases/download/v#{version}/tars_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "07f5493307cc6e77dceb19636607372e8a77353653383a9c460effa13ba4f907"
      url "https://github.com/cloudwalksolutions/machine-setup/releases/download/v#{version}/tars_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "f2d9bc44ab7a9958f9af8173ce0119ba0a19b1db2a4c4a30af2c2d2d5b7b6b3a"
      url "https://github.com/cloudwalksolutions/machine-setup/releases/download/v#{version}/tars_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "dfcea2517e1a969d0fbc12cea05c74f5e4924d62759826ff41b54dfb4b7bcadc"
      url "https://github.com/cloudwalksolutions/machine-setup/releases/download/v#{version}/tars_#{version}_linux_amd64.tar.gz"
    end
  end

  name "tars"
  desc "tars — dev-machine setup CLI (dotfiles, tools, fonts, terminals, byobu sessions, git profiles)"
  homepage "https://github.com/cloudwalksolutions/machine-setup"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tars"

  # No zap stanza required
end
