# This file was generated by GoReleaser. DO NOT EDIT.
cask "tars" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "46b1d54e4908daced29a3f0873c5d984ff2734d3ab8052df6238070a2c7005bd"
      url "https://github.com/cloudwalksolutions/machine-setup/releases/download/v#{version}/tars_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "43f951d5b4064cd3816055858a28d1d0deb150656d4dae0d545fa906a201ee6f"
      url "https://github.com/cloudwalksolutions/machine-setup/releases/download/v#{version}/tars_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "2db5c6a178836c10869944ce0cadc2c27f498f341ff31d2a1e308871d32fea33"
      url "https://github.com/cloudwalksolutions/machine-setup/releases/download/v#{version}/tars_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "a7eeeded57597fe37ea57eccf3a08edcfb5b480921755349e4970f24627bb678"
      url "https://github.com/cloudwalksolutions/machine-setup/releases/download/v#{version}/tars_#{version}_linux_amd64.tar.gz"
    end
  end

  name "tars"
  desc "CloudWalk dev-machine setup CLI (dotfiles, tools, fonts, terminals)"
  homepage "https://github.com/cloudwalksolutions/machine-setup"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tars"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tars"]
    end
  end

  # No zap stanza required
end
