# This file was generated by GoReleaser. DO NOT EDIT.
cask "tars" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/tars"]
    end
  end

  version "0.1.8"

  on_macos do
    on_arm do
      sha256 "5ecdfaf11e9f53e751a6a75dbc9c7964be4bb8c47902d3dfe3dad3ea4c92e4aa"
      url "https://github.com/cloudwalksolutions/machine-setup/releases/download/v#{version}/tars_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "761f2fc0b0faaab32eaa1a70dc48b0264d921b71f5d2f8b73b5522a3d04763f2"
      url "https://github.com/cloudwalksolutions/machine-setup/releases/download/v#{version}/tars_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "433b9b2f2ec6a6aff08177247579416ea32dd1bc46cbbf679a1a3f11d1661a79"
      url "https://github.com/cloudwalksolutions/machine-setup/releases/download/v#{version}/tars_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "6b1432e968bc9d0b96c2bc6e2aa9fa317f12a1ee6ed506e370e77681a506831b"
      url "https://github.com/cloudwalksolutions/machine-setup/releases/download/v#{version}/tars_#{version}_linux_amd64.tar.gz"
    end
  end

  name "tars"
  desc "tars — dev-machine setup CLI (dotfiles, tools, fonts, terminals, byobu sessions, git profiles)"
  homepage "https://github.com/cloudwalksolutions/machine-setup"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tars"

  # No zap stanza required
end
